version: '{build}'
install:
  - cmd: choco install sbt --version 1.0.2
  - cmd: set PATH=C:\Program Files (x86)\sbt\bin;%PATH%
build_script:
  - sbt compile
test_script:
  - sbt test
cache:
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:\Program Files (x86)\sbt -> appveyor.yml
  - C:\Users\appveyor\.ivy2
